# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754a78e274e11eacfd7ac4688fafbbc6ec8fe537b3c86bfb3a451dc7859d2413f307b06071fcf4f835926f4c7077485efeda97dea4b6a5cbbf11b64d5d2c8b1c

test:
  secret_key_base: db449bbf637fd254e10f39ad25789e683d1041313ee9156db99c0a580300b4e9ba3b6fbcbf0addaf19d2306e214447a323ad7667ce2599eebd89130c97750a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
